package HaskellFun.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenAspectBase;
import HaskellFun.structure.LanguageConceptSwitch;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.text.rt.TextGenDescriptor;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.text.rt.TextGenModelOutline;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class TextGenAspectDescriptor extends TextGenAspectBase {
  private final LanguageConceptSwitch myIndex = new LanguageConceptSwitch();

  public TextGenAspectDescriptor() {
  }

  @Nullable
  @Override
  public TextGenDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    switch (myIndex.index(concept)) {
      case LanguageConceptSwitch.Declaration:
        return new Declaration_TextGen();
      case LanguageConceptSwitch.DeclarationParameter:
        return new DeclarationParameter_TextGen();
      case LanguageConceptSwitch.DeclarationReference:
        return new DeclarationReference_TextGen();
      case LanguageConceptSwitch.DoExpression:
        return new DoExpression_TextGen();
      case LanguageConceptSwitch.EmptyLine:
        return new EmptyLine_TextGen();
      case LanguageConceptSwitch.HaskellModule:
        return new HaskellModule_TextGen();
      case LanguageConceptSwitch.Println:
        return new Println_TextGen();
    }
    return null;
  }

  @Override
  public void breakdownToUnits(@NotNull TextGenModelOutline outline) {
    for (SNode root : outline.getModel().getRootNodes()) {
      if (root.getConcept().equals(MetaAdapterFactory.getConcept(0x70eb8650b1874f45L, 0x995803d27f5d94baL, 0x325044962780d7d2L, "HaskellFun.structure.HaskellModule"))) {
        String fname = getFileName_HaskellModule(root);
        String ext = getFileExtension_HaskellModule(root);
        outline.registerTextUnit((ext == null ? fname : (fname + '.' + ext)), root);
        continue;
      }
    }
  }
  private static String getFileName_HaskellModule(SNode node) {
    return node.getName();
  }
  private static String getFileExtension_HaskellModule(SNode node) {
    return "fr";
  }
}
